'''
Created on Jul 20, 2013

@author: justin
'''

class Analyze(object):
    '''
    This class, is made up of a bunch of methods that are used to analyze stocks 
    at a granular level, and can be returned to the strategy class, for further 
    decision making
    '''
    
    def __init__(self):
        '''
        Constructor
        '''
        print 'Inside Analyze'
    
    def Technical(self):
        '''
        Technical
        Technical analysis of stock price charts identifies trading ranges, 
        price resistance and support. There are other indicators such as moving
        averages, relative strength, chart formations and various mathematical 
        analysis tools that attempt to define buying interest and selling interest, 
        and predict the price movement of the stock.
        '''
        
    def PriceEarningsRatio(self):
        '''
        Price-Earnings Ratio
        The price-earnings ratio attempts to discover whether the stock is trading
        cheap or rich. Find the P/E ratio by dividing the stock price by the 
        earnings-per-share. Compare this to other stocks in that industry to determine
        if your stock is fairly priced. Most stock quote services indicate the P/E ratio.
        '''
        return False
    
    def PriceToBook(self):
        '''
        Price-to-Book
        The price-to-book ratio attempts to show whether a stock is over-priced. 
        Take stockholders equity, which can be found in the company's balance sheet, 
        and dividing that by the number of shares outstanding. The lower the number 
        the better, but 1.5x is a good rule of thumb for fair value.
        '''
        return False
    
    def DebtToEquity(self):
        '''
        Debt-to-Equity
        The debt-to-equity ratio indicates whether the company carries too much debt.
        Divide stockholders equity into total liabilities to find the debt-to-equity 
        ratio. This is a number that must be compared to other companies in the same 
        industry because different industries use different levels of leverage. 
        The lower the number, in comparison with industry standards, the better.
        '''
        return False

    def FreeCashFlow(self):
        '''
        Free Cash Flow
        Find operating cash flow first by taking net income plus amortization and 
        depreciation, minus capital expenditures and dividends. Free cash flow includes 
        operating cash flow, plus or minus cash used or generated by investments 
        and financing. This indicates whether a company generates plenty of money 
        to operate and expand. Again, compare it to other companies in the industry.
        '''
        return False
        
    def PEGRatio(self):
        '''
        PEG Ratio
        Companies that have good financials but are not growing can result in a stock price
        that is not appreciating. To find the price-earnings-growth ratio, decide how many 
        years of earnings growth you want to use, five for example, and average the EPS
        growth over those five years, then divide that into the P/E ratio. The lower the
        number the better, because it means the stock is undervalued.
        '''
        return False
    
    
    
    def DeriveManagementQuality(self):
        '''
        Try to figure out a way to see if management quality at the company is acceptable.
        '''
        return False
    
    def GoogleSearches(self):
        '''
        derive a system to take into account the google searches that have taken place on
        this particualar company, or stock name
        ''' 
        
        
        
        
        
        
        
        
        
        
        return False
    
    
    